import { readdir, readFile } from 'node:fs/promises';
import path from 'node:path';

/**
 * `.lang` string-table parser — task 1.4e
 * ([plan-phase-1-foundation.md](../../../../Docs/plan-phase-1-foundation.md) §1.4e,
 * [spec-domain-reference.md](../../../../Docs/spec-domain-reference.md) L662-695,
 * decision D33(c)/(d)).
 *
 * Format (measured, spike 1.4a §5): **UTF-16LE with BOM `\xFF\xFE`**, header line
 * `1:{Category}`, then repeating records
 *
 * ```
 * {index}\r\n\r\n{value}\r\n
 * ```
 *
 * Scope is `Locale/en-US/*.lang` only — 5,132 files / 25.9 MB of the 33,932
 * files / 185 MB across all eight locales (D33(c)).
 *
 * ## Index radix — measured, and where it contradicts D33
 *
 * D33(d) prescribes the key ladder "all-digit suffix → decimal index first, then
 * hex". Spike 1.4a implemented that ladder for the **key** but only *skipped*
 * A–F-containing index tokens while reading the file, so 3,719 real records
 * (e.g. `1ED8A` → "Forged in Fire") were dropped and only 2,238 of 5,959 records
 * survived. Applying the ladder symmetrically to the file's index tokens
 * restores the whole table and resolves **315 of 315** keyed corpus quests
 * (the spike measured 48). The real-data evidence is in `scripts/sync-dry-run.ts`.
 *
 * One measured caveat is preserved and reported, not silently patched: an
 * all-digit index token is read as decimal per D33(d), so a later hex token with
 * the same numeric value overwrites it (e.g. `1ED8A` = 0x1ED8A = 126346
 * overwrites the record written as `126346`). That is why this module reports
 * `decimalRecordCount`/`hexRecordCount` and why `QuestTitle_1ED8D` resolves here
 * while D33(e) recorded it as absent.
 */

/** UTF-16LE byte-order mark (spike 1.4a §5). */
export const UTF16LE_BOM = Buffer.from([0xff, 0xfe]);

/** UTF-16BE BOM — never seen in this corpus; rejected explicitly. */
export const UTF16BE_BOM = Buffer.from([0xfe, 0xff]);

/** The header line: `1:{Category}`. */
const HEADER_PATTERN = /^\d+:(.*)$/;

/** Index tokens are hex (uppercase in the corpus, accepted in any case). */
const HEX_TOKEN_PATTERN = /^[0-9A-Fa-f]+$/;

/** All-digit index tokens take the decimal reading first (D33(d)). */
const DECIMAL_TOKEN_PATTERN = /^\d+$/;

export interface LangTable {
  /** Category from the header (`1:QuestTitle` → `QuestTitle`). */
  category: string;
  /** Numeric index → value. Later records win on a numeric collision. */
  entries: Map<number, string>;
  /** Records whose index token was non-empty (5,959 for `QuestTitle.lang`). */
  recordCount: number;
  /** Records read with the decimal ladder — the spike's "2,238 entries". */
  decimalRecordCount: number;
  /** Records read with the hex ladder (index token contained A–F). */
  hexRecordCount: number;
  /**
   * Named-key records (`ChooseFriendTitle` → `Choose Your Friend`) — the 79
   * tables keyed by name rather than by numeric index. `string_table.key` is TEXT,
   * so these are storable as `{Category}_{name}`.
   */
  namedEntries: Map<string, string>;
  /** Records with a named key (`namedEntries.size` plus name collisions). */
  namedRecordCount: number;
  /** Records whose named key overwrote an earlier record with the same key. */
  namedCollisionCount: number;
  /**
   * Records whose **middle line is non-blank**.
   *
   * The record shape is `{index}\r\n{middle}\r\n{value}\r\n`: the middle line
   * is empty in most tables (`QuestTitle`, `Items`, `GUI`, `Spell`) but carries a
   * secondary label in others (`MobDescriptions.lang` = the mob name above the
   * description, `ZoneLocName.lang` = "Quest location name (autogenerated)").
   * It is not a separator, and a non-blank middle line does **not** misalign the
   * parse (the stride is fixed at three lines).
   */
  nonBlankMiddleLineCount: number;
  /** Records whose index overwrote an earlier record with the same index. */
  collisionCount: number;
  /** Raw byte length of the parsed buffer. */
  byteLength: number;
  /** `true` when the buffer carried the UTF-16LE BOM. */
  hasBom: boolean;
}

export interface ParseLangOptions {
  /**
   * Category to use when the header line is missing/malformed. Production
   * `.lang` files always carry `1:{Category}`; this exists for defensive use.
   */
  categoryFallback?: string;
}

/** Strips the UTF-16LE BOM (when present) and decodes the body. */
export function decodeLangBuffer(buffer: Buffer | Uint8Array): {
  text: string;
  hasBom: boolean;
} {
  const bytes = Buffer.isBuffer(buffer) ? buffer : Buffer.from(buffer);
  if (bytes.length >= 2 && bytes[0] === UTF16BE_BOM[0] && bytes[1] === UTF16BE_BOM[1]) {
    throw new Error(
      'Unsupported .lang encoding: UTF-16BE BOM (0xFE 0xFF). The Imlight corpus is UTF-16LE (0xFF 0xFE).',
    );
  }
  const hasBom = bytes.length >= 2 && bytes[0] === UTF16LE_BOM[0] && bytes[1] === UTF16LE_BOM[1];
  const body = hasBom ? bytes.subarray(2) : bytes;
  return { text: body.toString('utf16le'), hasBom };
}

/**
 * Pure key→index conversion — the ladder from D33(d) applied to the suffix:
 * all-digit → decimal, otherwise → hex. `undefined` when the suffix is neither.
 *
 * ```
 * langKeyToIndex('1ED8D') === 126349   // 0x1ED8D, the spec's worked example
 * langKeyToIndex('00001717') === 1717  // padded decimal (the m_displayName form)
 * ```
 */
export function langKeyToIndex(suffix: string): number | undefined {
  const token = suffix.trim();
  if (token === '') {
    return undefined;
  }
  if (DECIMAL_TOKEN_PATTERN.test(token)) {
    const decimal = Number(token);
    return Number.isSafeInteger(decimal) ? decimal : undefined;
  }
  if (HEX_TOKEN_PATTERN.test(token)) {
    const hex = Number.parseInt(token, 16);
    return Number.isSafeInteger(hex) ? hex : undefined;
  }
  return undefined;
}

/** The `{suffix}` half of a `{Category}_{suffix}` key (split on the last `_`). */
export function langKeySuffix(key: string): string | undefined {
  const separator = key.lastIndexOf('_');
  if (separator <= 0 || separator === key.length - 1) {
    return undefined;
  }
  return key.slice(separator + 1);
}

/** The `{Category}` half of a `{Category}_{suffix}` key. */
export function langKeyCategory(key: string): string | undefined {
  const separator = key.lastIndexOf('_');
  if (separator <= 0) {
    return undefined;
  }
  return key.slice(0, separator);
}

/**
 * Inverse of the ladder: builds the canonical `{Category}_{index}` key that the
 * corpus uses in `m_displayName` values (8-digit zero-padded decimal —
 * `Items_00022716`, `QuestTitle_00001717`, `NPCs_01749407`). Pass
 * `{ style: 'hex' }` for the sparse-tail form (`QuestTitle_1ED8D`).
 */
export function formatLangKey(
  category: string,
  index: number,
  options: { style?: 'decimal' | 'hex'; pad?: number } = {},
): string {
  const style = options.style ?? 'decimal';
  const token =
    style === 'hex'
      ? index.toString(16).toUpperCase()
      : String(index).padStart(options.pad ?? 8, '0');
  return `${category}_${token}`;
}

/** A lookup table or a lookup function, both accepted (decision-friendly). */
export type LangLookup = Map<number, string> | ((index: number) => string | undefined);

function asLookupFn(lookup: LangLookup): (index: number) => string | undefined {
  return typeof lookup === 'function' ? lookup : (index) => lookup.get(index);
}

/**
 * Resolves `{Category}_{suffix}` through the D33(d) ladder: decimal first for an
 * all-digit suffix, then hex, then `undefined` (the caller shows the raw key —
 * a miss is normal, [spec-domain-reference.md] L694-695).
 */
export function resolveLangKey(key: string, lookup: LangLookup): string | undefined {
  const suffix = langKeySuffix(key);
  if (suffix === undefined) {
    return undefined;
  }
  const get = asLookupFn(lookup);

  if (DECIMAL_TOKEN_PATTERN.test(suffix)) {
    const value = get(Number(suffix));
    if (value !== undefined) {
      return value;
    }
  }
  if (HEX_TOKEN_PATTERN.test(suffix)) {
    const value = get(Number.parseInt(suffix, 16));
    if (value !== undefined) {
      return value;
    }
  }
  return undefined;
}

/**
 * `true` when the line can start a record.
 *
 * Three key forms exist in the corpus, all in the same three-line record shape
 * `{key}\r\n{middle}\r\n{value}\r\n`:
 *
 *  - zero-padded decimal (`00000000`, `QuestTitle.lang` and ~5,050 more);
 *  - hex (`1ED8D`, the sparse tail of `QuestTitle.lang`);
 *  - **named** (`ChooseFriendTitle` in `ChooseFriendSWF.lang`, `CLASS_ANSWER_1_A_1`
 *    in `CharCreation.lang`, `QuestFinder` in `QuestTitle.lang`) — 79 tables are
 *    named-keyed and would be dropped entirely by a numeric-only rule.
 *
 * A line qualifies when it is a single token that is either hex-shaped or starts
 * with a letter. Multi-word values (`Quest location name (autogenerated)`,
 * `<ITALICS>You find…`) never qualify, so they are not mistaken for a first index.
 */
function isIndexToken(line: string): boolean {
  const token = line.trim();
  if (token === '' || /\s/.test(token)) {
    return false;
  }
  return HEX_TOKEN_PATTERN.test(token) || /^[A-Za-z]/.test(token);
}

/**
 * Parses one `.lang` buffer.
 *
 * The record layout is positional and three lines wide —
 * `{index}\r\n{middle}\r\n{value}\r\n` — because an empty value would otherwise
 * swallow the next index (spike 1.4a §5: "indices are not always zero-padded";
 * `QuestTitle.lang` has records with an empty value). Reading starts at the first
 * line after the header that parses as an index token and then strides by three;
 * the middle line is a secondary label (empty in most tables, a name/description
 * in others) and is reported through `nonBlankMiddleLineCount`.
 *
 * The three-line shape is verified against real cross-references: a Wizard City
 * tutorial quest (`Tutorials/WC-PreCel-MAIN-001`) carries
 * `m_locationName: "ZoneLocName_595390"` with the *Diego the Duelmaster* portrait
 * and `m_zoneTag: "WizardCity/WC_Ravenwood"`, and this parser resolves that key to
 * `"Wizard City|Unicorn Way"` — the third line. Pairing the index with the
 * preceding line instead would yield `"MooShu|Cave of Solitude"`.
 */
export function parseLangBuffer(
  buffer: Buffer | Uint8Array,
  options: ParseLangOptions = {},
): LangTable {
  const bytes = Buffer.isBuffer(buffer) ? buffer : Buffer.from(buffer);
  const { text, hasBom } = decodeLangBuffer(bytes);
  const lines = text.split(/\r\n|\n/);
  const [firstLine = '', ...rest] = lines;
  const header = firstLine.trim();
  const match = HEADER_PATTERN.exec(header);
  // Without a recognisable header the whole buffer is body (the fallback path).
  const body = match ? rest : lines;
  const category = match?.[1] || options.categoryFallback;
  if (category === undefined || category === '') {
    throw new Error(
      `Not a .lang string table: first line is ${JSON.stringify(header)} but expected "1:{Category}" ` +
        `(e.g. "1:QuestTitle"). Pass { categoryFallback } when the header is known to be absent.`,
    );
  }

  let start = 0;
  while (start < body.length && !isIndexToken(body[start])) {
    start += 1;
  }

  const entries = new Map<number, string>();
  const namedEntries = new Map<string, string>();
  let namedCollisionCount = 0;
  let recordCount = 0;
  let decimalRecordCount = 0;
  let hexRecordCount = 0;
  let nonBlankMiddleLineCount = 0;
  let collisionCount = 0;

  for (let i = start; i + 1 < body.length; i += 3) {
    const token = body[i].trim();
    const separator = body[i + 1];
    const value = body[i + 2] ?? '';
    if (token === '') {
      continue;
    }
    recordCount += 1;
    if (separator.trim() !== '') {
      nonBlankMiddleLineCount += 1;
    }
    if (DECIMAL_TOKEN_PATTERN.test(token)) {
      decimalRecordCount += 1;
    } else if (HEX_TOKEN_PATTERN.test(token)) {
      hexRecordCount += 1;
    }
    const index = langKeyToIndex(token);
    if (index === undefined) {
      if (namedEntries.has(token)) {
        namedCollisionCount += 1;
      }
      namedEntries.set(token, value);
      continue;
    }
    if (entries.has(index)) {
      collisionCount += 1;
    }
    entries.set(index, value);
  }

  return {
    category,
    entries,
    recordCount,
    decimalRecordCount,
    hexRecordCount,
    namedEntries,
    namedRecordCount: namedEntries.size + namedCollisionCount,
    namedCollisionCount,
    nonBlankMiddleLineCount,
    collisionCount,
    byteLength: bytes.length,
    hasBom,
  };
}

export interface LangDirDeps {
  readdir: (dir: string) => Promise<string[]>;
  readFile: (file: string) => Promise<Buffer>;
}

export const defaultLangDirDeps: LangDirDeps = {
  readdir: (dir) => readdir(dir),
  readFile: (file) => readFile(file),
};

export interface ScanLangDirResult {
  /** One parsed table per `*.lang` file, ordered by file name. */
  tables: Array<{ file: string } & LangTable>;
  /** Total `*.lang` files parsed. */
  fileCount: number;
  /** Total bytes of those files. */
  byteCount: number;
  /** Sum of `entries.size` across tables — the `string_table` row count. */
  rowCount: number;
  /** Same, counting only non-empty values (empty strings are corpus noise). */
  nonEmptyRowCount: number;
  /** Named-key records across all tables (`ChooseFriendTitle` → `Choose Your Friend`). */
  namedRowCount: number;
  /** Records whose middle line carried a secondary label (a third column). */
  namedRecordCount: number;
  /** Records whose index overwrote an earlier record with the same index. */
  collisionCount: number;
  /** `entries` merged per category (the lookup the templates need). */
  byCategory: Map<string, Map<number, string>>;
  /** `namedEntries` merged per category. */
  namedByCategory: Map<string, Map<string, string>>;
  /** Files that could not be parsed. A corrupt locale file must not abort a sync. */
  errors: Array<{ file: string; message: string }>;
}

export interface ScanLangDirOptions {
  deps?: Partial<LangDirDeps>;
  /** Bounded read concurrency — 5,132 small files on the real corpus. */
  concurrency?: number;
}

/**
 * Parses every `*.lang` in a locale directory (production:
 * `{tempDir}/Locale/en-US`) and merges the entries per category.
 *
 * Injected filesystem so unit tests run against tiny synthetic directories and
 * so nothing in the test suite reads the real unpack tree.
 */
export async function scanLangDir(
  localeDir: string,
  options: ScanLangDirOptions = {},
): Promise<ScanLangDirResult> {
  const deps: LangDirDeps = { ...defaultLangDirDeps, ...options.deps };
  const concurrency = Math.max(1, options.concurrency ?? 32);

  let names: string[];
  try {
    names = (await deps.readdir(localeDir)).filter((name) => name.endsWith('.lang')).sort();
  } catch (error) {
    throw new Error(
      `Could not list .lang files under ${localeDir}: ${
        error instanceof Error ? error.message : String(error)
      }. Expected the unpacked tree's Locale/en-US directory.`,
    );
  }

  const tables: ScanLangDirResult['tables'] = [];
  const errors: ScanLangDirResult['errors'] = [];
  let byteCount = 0;
  let rowCount = 0;
  let nonEmptyRowCount = 0;
  let namedRecordCount = 0;
  let namedRowCount = 0;
  let collisionCount = 0;

  for (let offset = 0; offset < names.length; offset += concurrency) {
    const batch = names.slice(offset, offset + concurrency);
    const parsed = await Promise.all(
      batch.map(async (name) => {
        const file = path.join(localeDir, name);
        try {
          const buffer = await deps.readFile(file);
          const table = parseLangBuffer(buffer, {
            categoryFallback: path.basename(name, '.lang'),
          });
          return { file, table, size: buffer.byteLength };
        } catch (error) {
          errors.push({ file, message: error instanceof Error ? error.message : String(error) });
          return undefined;
        }
      }),
    );
    for (const entry of parsed) {
      if (!entry) {
        continue;
      }
      tables.push({ file: entry.file, ...entry.table });
      byteCount += entry.size;
      rowCount += entry.table.entries.size;
      namedRecordCount += entry.table.nonBlankMiddleLineCount;
      namedRowCount += entry.table.namedEntries.size;
      collisionCount += entry.table.collisionCount;
      for (const value of entry.table.entries.values()) {
        if (value !== '') {
          nonEmptyRowCount += 1;
        }
      }
    }
  }

  const byCategory = new Map<string, Map<number, string>>();
  const namedByCategory = new Map<string, Map<string, string>>();
  for (const table of tables) {
    const merged = byCategory.get(table.category) ?? new Map<number, string>();
    for (const [index, value] of table.entries) {
      merged.set(index, value);
    }
    byCategory.set(table.category, merged);

    const mergedNamed = namedByCategory.get(table.category) ?? new Map<string, string>();
    for (const [key, value] of table.namedEntries) {
      mergedNamed.set(key, value);
    }
    namedByCategory.set(table.category, mergedNamed);
  }

  return {
    tables,
    fileCount: tables.length,
    byteCount,
    rowCount,
    nonEmptyRowCount,
    namedRowCount,
    namedRecordCount,
    collisionCount,
    byCategory,
    namedByCategory,
    errors,
  };
}

/**
 * Builds the `key → value` resolver the template/quest parsers need: splits the
 * key into `{Category}_{suffix}`, runs the D33(d) numeric ladder, and — when the
 * named tables are supplied — falls back to a named-key lookup.
 *
 * Named keys may themselves contain underscores (`CLASS_ANSWER_1_A_1`), so the
 * named path splits on the **first** underscore instead of the last.
 */
export function createKeyLookup(
  byCategory: Map<string, Map<number, string>>,
  namedByCategory?: Map<string, Map<string, string>>,
): (key: string) => string | undefined {
  return (key) => {
    const category = langKeyCategory(key);
    if (category !== undefined) {
      const table = byCategory.get(category);
      if (table) {
        const resolved = resolveLangKey(key, table);
        if (resolved !== undefined) {
          return resolved;
        }
      }
    }
    if (!namedByCategory) {
      return undefined;
    }
    const separator = key.indexOf('_');
    if (separator <= 0) {
      return undefined;
    }
    return namedByCategory.get(key.slice(0, separator))?.get(key.slice(separator + 1));
  };
}
